/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'background': '#06080d',
        'surface': '#10131a',
        'surface-dim': '#10131a',
        'surface-bright': '#363941',
        'surface-container-lowest': '#0b0e15',
        'surface-container-low': '#191b23',
        'surface-container': '#1d1f27',
        'surface-container-high': '#272a32',
        'surface-container-highest': '#32353d',
        'surface-variant': '#32353d',
        'on-surface': '#e1e2ec',
        'on-surface-variant': '#bdc8d1',
        'inverse-surface': '#e1e2ec',
        'inverse-on-surface': '#2d3038',
        'outline': '#87929a',
        'outline-variant': '#3e484f',
        'surface-tint': '#7bd0ff',
        'primary': '#8ed5ff',
        'on-primary': '#00354a',
        'primary-container': '#38bdf8',
        'on-primary-container': '#004965',
        'inverse-primary': '#00668a',
        'primary-fixed': '#c4e7ff',
        'primary-fixed-dim': '#7bd0ff',
        'secondary': '#bdc2ff',
        'on-secondary': '#131e8c',
        'secondary-container': '#2f3aa3',
        'on-secondary-container': '#a8afff',
        'secondary-fixed': '#e0e0ff',
        'secondary-fixed-dim': '#bdc2ff',
        'tertiary': '#4ee6aa',
        'on-tertiary': '#003825',
        'tertiary-container': '#22c990',
        'on-tertiary-container': '#004e35',
        'tertiary-fixed': '#68fcbf',
        'tertiary-fixed-dim': '#45dfa4',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'status-safe': '#10b981',
        'status-warning': '#f59e0b',
        'status-danger': '#f43f5e',
      },
      borderRadius: {
        'sm': '0.5rem',
        'DEFAULT': '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
      },
      fontFamily: {
        'headline': ['"Space Grotesk"', 'sans-serif'],
        'body': ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'mono': ['"JetBrains Mono"', 'monospace'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-xl': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'display-hero': ['"Space Grotesk"', 'sans-serif'],
        'title-sm': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'label-data-lg': ['"JetBrains Mono"', 'monospace'],
        'label-data-md': ['"JetBrains Mono"', 'monospace'],
        'label-caps': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'label-data-md': ['14px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'title-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'label-data-lg': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '600' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '600' }],
      }
    },
  },
  plugins: [],
}
